-- MySQL Script generated by MySQL Workbench
-- Wed May  3 21:50:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TG_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TG_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TG_school` DEFAULT CHARACTER SET utf8mb3 ;
USE `TG_school` ;

-- -----------------------------------------------------
-- Table `TG_school`.`quests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TG_school`.`quests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `solution` LONGTEXT NOT NULL,
  `class` INT NULL DEFAULT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TG_school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TG_school`.`users` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `class` INT NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TG_school`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TG_school`.`rating` (
  `count` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_rating_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `TG_school`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TG_school`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TG_school`.`test` (
  `id_user` INT NOT NULL,
  `id_quest` INT NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `is_suc` TINYINT NOT NULL,
  `attempt` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_quest`),
  INDEX `fk_users_has_quests_quests1_idx` (`id_quest` ASC) VISIBLE,
  INDEX `fk_users_has_quests_users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_quests_quests1`
    FOREIGN KEY (`id_quest`)
    REFERENCES `TG_school`.`quests` (`id`),
  CONSTRAINT `fk_users_has_quests_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `TG_school`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
